# Generated by Django 5.1.4 on 2024-12-22 12:08

import datetime
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillBgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('date', models.CharField(max_length=60)),
                ('number', models.IntegerField()),
                ('company', models.CharField(default='default-company', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='BillSld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False)),
                ('customer', models.CharField(max_length=60)),
                ('date', models.CharField(max_length=60)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='بدون نام', max_length=25)),
                ('company', models.CharField(max_length=25)),
                ('existing_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('photo', models.ImageField(default='static\\UsedPhoto\\BedonAks.jpg', null=True, upload_to='drugs/')),
                ('description', models.TextField(blank=True, default='بدون جزئیات')),
                ('unique', models.CharField(blank=True, default='no name and company', max_length=60, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', '-created'],
                'indexes': [models.Index(fields=['-created'], name='main_drug_created_44f575_idx'), models.Index(fields=['name'], name='main_drug_name_bffea9_idx'), models.Index(fields=['company'], name='main_drug_company_f91d44_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='بدون نام', max_length=25)),
                ('company', models.CharField(default='بدون شرکت', max_length=25)),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('date', django_jalali.db.models.jDateField(default=datetime.date(2024, 12, 22))),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drugs')),
                ('bgt_bill', models.PositiveSmallIntegerField(default=0, verbose_name='bill')),
                ('unique', models.CharField(blank=True, max_length=100, unique=True)),
                ('currency', models.CharField(default='AFS', max_length=3)),
                ('sld_amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10)),
                ('baqi_amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('Buyer', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('bill_object', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bgts', to='main.billbgt')),
                ('drug', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Purchases', to='main.drug')),
            ],
            options={
                'verbose_name': 'Purchase',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوای یادداشت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('importance', models.PositiveSmallIntegerField(choices=[(1, 'very important'), (2, 'important'), (3, 'Easy')], verbose_name='اولویت')),
                ('author', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['importance'],
            },
        ),
        migrations.CreateModel(
            name='Sld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='بدون نام', max_length=30)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('date', django_jalali.db.models.jDateField(default=datetime.date(2024, 12, 22))),
                ('company', models.CharField(default='بدون شرکت', max_length=30)),
                ('customer', models.CharField(default='نا مشخص', max_length=30)),
                ('profite', models.DecimalField(blank=True, decimal_places=1, max_digits=10)),
                ('sld_bill', models.IntegerField(default=0, verbose_name='bill')),
                ('currency', models.CharField(blank=True, default='AFS', max_length=3)),
                ('unique', models.CharField(blank=True, max_length=100, unique=True)),
                ('total', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('bgt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.bgt', verbose_name='Purchase')),
                ('bill_object', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slds', to='main.billsld')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slds', to='main.drug')),
                ('seller', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='bgt',
            index=models.Index(fields=['name'], name='main_bgt_name_ee65a3_idx'),
        ),
        migrations.AddIndex(
            model_name='bgt',
            index=models.Index(fields=['company'], name='main_bgt_company_32752e_idx'),
        ),
        migrations.AddIndex(
            model_name='bgt',
            index=models.Index(fields=['-date'], name='main_bgt_date_f0244d_idx'),
        ),
        migrations.AddIndex(
            model_name='sld',
            index=models.Index(fields=['name'], name='main_sld_name_34b3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='sld',
            index=models.Index(fields=['-date'], name='main_sld_date_344907_idx'),
        ),
    ]
