# Generated by Django 5.1.4 on 2024-12-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bgt_expire_date_alter_bgt_buyer_alter_bgt_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgt',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='bgt',
            name='expire_days',
            field=models.SmallIntegerField(default=1095),
        ),
    ]
