# Generated by Django 5.1.4 on 2025-01-01 03:54

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_bgt_expire_date_bgt_expire_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgt',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='sld',
            name='currency',
        ),
        migrations.AlterField(
            model_name='bgt',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AlterField(
            model_name='sld',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2025, 1, 1)),
        ),
    ]
