# Generated by Django 5.1.4 on 2025-01-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_bgt_currency_remove_sld_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgt',
            old_name='expire_days',
            new_name='expire_months',
        ),
    ]
