# Generated by Django 5.1.4 on 2025-01-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_loan_alter_bgt_date_alter_sld_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='client_id',
            field=models.FileField(upload_to='loan/ids/'),
        ),
    ]
